theme: jekyll-theme-minimal
title: GREW-MRS
description: This repository is a code accompaniment to my Masters-level thesis project on Swarm Systems and their applicability to Green Wall System maintenance.
